/* eslint-disable @next/next/no-img-element */
import { money, shortDate } from "@/lib/format";
import type { DocumentData } from "@/lib/invoice";
import { PrintButton } from "@/components/PrintButton";

export function DocumentView({data,label}:{data:DocumentData;label:"Invoice"|"Quote"}){
  const {form,services,config,seller}=data; const discounted=Number(form.total)-Number(form.discount);const tax=Math.max(0,Number(form.final_amount)-discounted);
  return <main className="document-shell"><article className="document"><header className="document-head"><div>{config.logo&&<img src={config.logo} alt="Company logo" style={{maxWidth:180,maxHeight:90,objectFit:"contain",marginBottom:18}}/>}<h1 className="document-title">{label}</h1></div><div className="document-meta"><strong>#{form.invoiceNumber}</strong><p>{shortDate(form.createdAt)}</p><div className="actions no-print"><PrintButton/><a className="button secondary" href={`/api/forms/${form.formId}/pdf?uuid=${form.invoiceUuid}&type=${form.type}`}>Download PDF</a></div></div></header><section className="document-addresses"><div><span className="eyebrow">From</span><h3>{config.company_name||"Simsan Fraser Maintenance"}</h3><p>{config.company_address}<br/>{config.company_city} {config.company_zip}<br/>{config.company_country||"Canada"}</p>{config.gst&&<p>GST: {config.gst}</p>}<p className="muted">Prepared by {seller}</p></div><div><span className="eyebrow">Bill to</span><h3>{form.customerName}</h3><p>{form.customerEmail}<br/>{form.customerPhone}<br/>{form.customerAddress}<br/>{form.customerCity}, {form.customerProvince} {form.customerPostalCode}<br/>{form.customerCountry}</p></div></section><div className="table-wrap"><table><thead><tr><th>Service</th><th>Quantity</th><th style={{textAlign:"right"}}>Price</th></tr></thead><tbody>{services.map(service=><tr key={service.id}><td>{service.serviceName}</td><td>1</td><td style={{textAlign:"right"}}>{money(service.price)}</td></tr>)}</tbody></table></div><section className="totals" style={{marginTop:30}}><div className="total-row"><span>Subtotal</span><strong>{money(form.total)}</strong></div>{Number(form.discount)>0&&<div className="total-row"><span>Discount ({Number(form.discount_percent).toFixed(2)}%)</span><strong>− {money(form.discount)}</strong></div>}{form.is_taxable&&<div className="total-row"><span>GST (5%)</span><strong>{money(tax)}</strong></div>}<div className="total-row grand"><span>Total CAD</span><strong>{money(form.final_amount)}</strong></div></section>{form.comment&&<section style={{marginTop:45,borderTop:"1px solid var(--line)",paddingTop:20}}><span className="eyebrow">Notes</span><p>{form.comment}</p></section>}<footer style={{marginTop:55,color:"var(--muted)",fontSize:13}}>Thank you for choosing Simsan Fraser Maintenance.</footer></article></main>
}
