"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { api } from "@/lib/client-api";
import { money, shortDate } from "@/lib/format";
import type { Service } from "@/lib/types";

interface PageData{rows:Service[];total:number}
export function ServicesManager(){
  const [data,setData]=useState<PageData>({rows:[],total:0});const [page,setPage]=useState(0);const [editing,setEditing]=useState<Service|null|"new">(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  const load=useCallback(()=>api<PageData>(`/api/services?skip=${page*10}&limit=10`).then(setData).catch(e=>setError(e.message)),[page]);useEffect(()=>{load()},[load]);
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const values=Object.fromEntries(new FormData(e.currentTarget));const current=editing!=="new"?editing:null;try{await api(current?`/api/services/${current.serviceId}`:"/api/services",{method:current?"PUT":"POST",body:JSON.stringify(values)});setEditing(null);await load()}catch(err){setError(err instanceof Error?err.message:"Save failed")}finally{setBusy(false)}}
  async function toggle(service:Service){try{await api(`/api/services/${service.serviceId}`,{method:"DELETE"});await load()}catch(e){setError(e instanceof Error?e.message:"Update failed")}}
  const current=editing!=="new"?editing:null;
  return <><div className="page-head"><div><span className="eyebrow">Price catalogue</span><h1>Services</h1><p>{data.total} services available for quotes and invoices.</p></div><button className="button" onClick={()=>setEditing(editing?null:"new")}>{editing?"Close form":"Add service"}</button></div>{error&&<div className="error" style={{marginBottom:16}}>{error}</div>}{editing&&<form className="card form-stack" onSubmit={save} style={{marginBottom:20}}><h2>{current?"Edit":"Create"} service</h2><div className="form-grid"><Field label="Service name"><input name="serviceName" defaultValue={current?.serviceName} required/></Field><Field label="Price"><input name="price" type="number" min="0" step="0.01" defaultValue={current?.price||0} required/></Field><Field label="Priority"><input name="priority" type="number" min="0" defaultValue={current?.priority||0}/></Field><Field label="Status"><select name="isActive" defaultValue={current?.isActive??1}><option value="1">Active</option><option value="0">Inactive</option></select></Field></div><div><button className="button" disabled={busy}>{busy?"Saving…":"Save service"}</button></div></form>}<section className="card"><div className="table-wrap"><table><thead><tr><th>Priority</th><th>Service</th><th>Price</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>{data.rows.map(service=><tr key={service.serviceId}><td>{service.priority??"—"}</td><td><strong>{service.serviceName}</strong>{service.isDeleted&&<><br/><span className="badge off">Deleted</span></>}</td><td>{money(service.price)}</td><td><span className={`badge ${service.isActive&&!service.isDeleted?"":"off"}`}>{service.isActive&&!service.isDeleted?"Active":"Inactive"}</span></td><td>{shortDate(service.createdAt)}</td><td><div className="actions"><button className="button small secondary" onClick={()=>setEditing(service)}>Edit</button><button className={`button small secondary ${service.isDeleted?"":"danger"}`} onClick={()=>toggle(service)}>{service.isDeleted?"Restore":"Delete"}</button></div></td></tr>)}</tbody></table></div><div className="pagination"><button className="button small secondary" disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><button className="button small secondary" disabled={(page+1)*10>=data.total} onClick={()=>setPage(p=>p+1)}>Next</button></div></section></>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="field"><label>{label}</label>{children}</div>}
