"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { api } from "@/lib/client-api";
import { shortDate } from "@/lib/format";
import type { User } from "@/lib/types";

interface PageData{rows:User[];total:number}
export function UsersManager(){
  const [data,setData]=useState<PageData>({rows:[],total:0});const [page,setPage]=useState(0);const [show,setShow]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
  const load=useCallback(()=>api<PageData>(`/api/users?skip=${page*10}&limit=10`).then(setData).catch(e=>setError(e.message)),[page]);useEffect(()=>{load()},[load]);
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);try{await api("/api/users",{method:"POST",body:JSON.stringify(Object.fromEntries(f))});setShow(false);setMessage("User created. A verification email is sent when SMTP is configured.");await load()}catch(err){setError(err instanceof Error?err.message:"Create failed")}finally{setBusy(false)}}
  async function status(user:User){try{await api(`/api/users/${user.id}`,{method:"PATCH",body:JSON.stringify({is_active:user.is_active?0:1})});await load()}catch(e){setError(e instanceof Error?e.message:"Update failed")}}
  async function remove(user:User){if(!confirm(`Delete ${user.first_name} ${user.last_name}?`))return;try{await api(`/api/users/${user.id}`,{method:"DELETE"});await load()}catch(e){setError(e instanceof Error?e.message:"Delete failed")}}
  return <><div className="page-head"><div><span className="eyebrow">Access control</span><h1>Users</h1><p>{data.total} active user records.</p></div><button className="button" onClick={()=>setShow(v=>!v)}>{show?"Close form":"Add user"}</button></div>{error&&<div className="error" style={{marginBottom:16}}>{error}</div>}{message&&<div className="success" style={{marginBottom:16}}>{message}</div>}{show&&<form className="card form-stack" onSubmit={create} style={{marginBottom:20}}><h2>Create user</h2><div className="form-grid"><Field label="First name"><input name="first_name" required/></Field><Field label="Last name"><input name="last_name" required/></Field><Field label="Email"><input name="email" type="email" required/></Field><Field label="Mobile number"><input name="mobile_no" required/></Field><Field label="Temporary password"><input name="password" type="password" minLength={8} required/></Field><Field label="Role"><select name="roles"><option value="sub_admin">Sub administrator</option><option value="admin">Administrator</option></select></Field></div><div><button className="button" disabled={busy}>{busy?"Creating…":"Create user"}</button></div></form>}<section className="card"><div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Verified</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>{data.rows.map(user=><tr key={user.id}><td><strong>{user.first_name} {user.last_name}</strong></td><td>{user.email}</td><td><span className="badge">{user.roles.replace("_"," ")}</span></td><td>{user.is_verified?"Yes":"No"}</td><td><span className={`badge ${user.is_active?"":"off"}`}>{user.is_active?"Active":"Inactive"}</span></td><td>{shortDate(user.createdAt)}</td><td><div className="actions"><button className="button small secondary" onClick={()=>status(user)}>{user.is_active?"Deactivate":"Activate"}</button><button className="button small secondary danger" onClick={()=>remove(user)}>Delete</button></div></td></tr>)}</tbody></table>{!data.rows.length&&<div className="empty">No users found.</div>}</div><div className="pagination"><button className="button small secondary" disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><button className="button small secondary" disabled={(page+1)*10>=data.total} onClick={()=>setPage(p=>p+1)}>Next</button></div></section></>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="field"><label>{label}</label>{children}</div>}
